[package]
name = "demo"
version = "0.0.0"
edition = "2021"

[dependencies]
prost = "0.13.2"
tonic = "0.12.2"
tonic-build = "0.12.2"
tokio = { version = "1.40.0", features = ["rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.12.2"
